// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChCToY7fB7IOzwTz4T_lCGw8-jlIRwu8w',
    appId: '1:613054248594:web:4568776af331dda6bc184b',
    messagingSenderId: '613054248594',
    projectId: 'wenshiji',
    authDomain: 'wenshiji.firebaseapp.com',
    storageBucket: 'wenshiji.firebasestorage.app',
    measurementId: 'G-N96J2M24LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZECo5eR7AlrHtnRZHt4FBQueHkZRXSQM',
    appId: '1:613054248594:android:3367587c1638bf7dbc184b',
    messagingSenderId: '613054248594',
    projectId: 'wenshiji',
    storageBucket: 'wenshiji.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqr1yWe64-58Ptig9s8o_vP2sjO1rf37g',
    appId: '1:613054248594:ios:eb02ccc69b3d9ccfbc184b',
    messagingSenderId: '613054248594',
    projectId: 'wenshiji',
    storageBucket: 'wenshiji.firebasestorage.app',
    iosBundleId: 'com.example.birthdayCountdown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqr1yWe64-58Ptig9s8o_vP2sjO1rf37g',
    appId: '1:613054248594:ios:eb02ccc69b3d9ccfbc184b',
    messagingSenderId: '613054248594',
    projectId: 'wenshiji',
    storageBucket: 'wenshiji.firebasestorage.app',
    iosBundleId: 'com.example.birthdayCountdown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChCToY7fB7IOzwTz4T_lCGw8-jlIRwu8w',
    appId: '1:613054248594:web:486cf0ebb754e17fbc184b',
    messagingSenderId: '613054248594',
    projectId: 'wenshiji',
    authDomain: 'wenshiji.firebaseapp.com',
    storageBucket: 'wenshiji.firebasestorage.app',
    measurementId: 'G-0X6VJLR0BN',
  );
}
